name: Build Plugin

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: dotnet restore QuickLook.Plugin.SumatraPDFReader\QuickLook.Plugin.SumatraPDFReader.csproj

      - name: Build (Release)
        run: msbuild QuickLook.Plugin.SumatraPDFReader\QuickLook.Plugin.SumatraPDFReader.csproj /p:Configuration=Release /p:Platform="Any CPU" /p:OutputPath="${{ github.workspace }}\out\"

      - name: Upload DLL artifact
        uses: actions/upload-artifact@v4
        with:
          name: QuickLook.Plugin.SumatraPDFReader
          path: ${{ github.workspace }}\out\QuickLook.Plugin.SumatraPDFReader.dll
